// Trycatch 

const numero1 = 20;
const numero3 = 30;

console.log(numero1);
// console.log(numero2);  //Encuentra error y deja de ejecutar 
try{
    console.log(numero2);
}catch(error){
    console.log(error);
}
console.log(numero3);